{%set name = "Cheroot" %}
{%set version = "5.4.0" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "f4b3d2eaa949b8a2f6676e3bca7c68cd358e4aa6bab437362b4bee6781626135" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm

  run:
    - python
    - six

test:
  imports:
    - cheroot
    - cheroot.test


about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Highly-optimized, pure-python HTTP server'
  dev_url: https://github.com/cherrypy/cheroot
  doc_url: http://www.cherrypy.org

extra:
  recipe-maintainers:
    - pmlandwehr
