{% set name = "Cheroot" %}
{% set version = "11.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: bfb70c49663f63b0440f2b54dbc6b0d1650e56dfe4e2641f59b2c6f727b44aca

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - cheroot = cheroot.cli:main

requirements:
  host:
    - python
    - pip
    - setuptools >=61.2
    - setuptools-scm >=7.0.0
  run:
    - python
    - more-itertools >=2.6
    - jaraco.functools

{% set tests_to_ignore = "" %}
# E   ModuleNotFoundError: No module named 'requests_unixsocket'
{% set tests_to_ignore = " --ignore=${SP_DIR}/cheroot/test/test_server.py" %}  # [unix]
{% set tests_to_ignore = " --ignore=%SP_DIR%/cheroot/test/test_server.py" %}  # [win]
# E   ModuleNotFoundError: No module named 'requests_toolbelt'
{% set tests_to_ignore = tests_to_ignore + " --ignore=${SP_DIR}/cheroot/test/test_wsgi.py" %}  # [unix]
{% set tests_to_ignore = tests_to_ignore + " --ignore=%SP_DIR%/cheroot/test/test_wsgi.py" %}  # [win]

# On Windows, the SSL handshake failure is producing an error message that differs from all the predefined expected patterns,
# causing the assertion assert any(e in err_text for e in expected_substrings) to fail since none of the expected substring patterns are found in the actual error text.
{% set tests_to_ignore = tests_to_ignore + " --ignore=%SP_DIR%/cheroot/test/test_ssl.py" %}  # [win]

test:
  imports:
    - cheroot
    - cheroot.cli
    - cheroot.server
    - cheroot.test
    - cheroot.wsgi
  commands:
    - pip check
    - cheroot --help
    - pytest -v ${SP_DIR}/cheroot/test {{ tests_to_ignore }}  # [unix]
    - pytest -v %SP_DIR%/cheroot/test {{ tests_to_ignore }}  # [win]
  requires:
    - pip
    - pytest >=7
    - pytest-mock >=1.11.0
    - pytest-rerunfailures
    - pytest-sugar >=0.9.3
    - pytest-xdist >=1.28.0
    - requests
    - jaraco.text >=3.1
    - pyopenssl >=22
    - portend
    - trustme >=0.4.0

about:
  home: https://cheroot.cherrypy.dev
  summary: Cheroot is the high-performance, pure-Python HTTP server used by CherryPy.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  description: Cheroot is the high-performance, pure-Python HTTP server used by CherryPy.
  dev_url: https://github.com/cherrypy/cheroot
  doc_url: https://cheroot.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
