{% set name = "Cheroot" %}
{% set version = "6.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: f6a85e005adb5bc5f3a92b998ff0e48795d4d98a0fbb7edde47a7513d4100601

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0
  run:
    - python
    - six >=1.11.0
    - more-itertools >=2.6
    - backports.functools_lru_cache

test:
  imports:
    - cheroot
    - cheroot.test

about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Highly-optimized, pure-python HTTP server'
  dev_url: https://github.com/cherrypy/cheroot
  doc_url: https://cheroot.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
    - carlodri
