{% set name = "Cheroot" %}
{% set version = "6.2.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "f50723330f84898fdc16a945689ac6038b137f84f44d20bc4702a1a02171bad4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name|lower }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - pip
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0

  run:
    - python
    - six >=1.11.0
    - more-itertools >=2.6
    - backports.functools_lru_cache  # [py2k]

test:
  imports:
    - cheroot
    - cheroot.test


about:
  home: http://www.cherrypy.org
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Highly-optimized, pure-python HTTP server'
  dev_url: https://github.com/cherrypy/cheroot
  doc_url: https://cheroot.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
