travis:
  secure:
    BINSTAR_TOKEN: C7amMauIIKyDHaFxBwoqHTGss5GyelwZ/vu06klSWhuJTyuU/sAEHQKY6DGDZjtFBabF8L7Y0jHkEENl6VGS0VebVXLRXBePWi4CoGfMU0feHiq0a0wPqhQItszdlspP/3mFK6saQfN3D/SedCoDr/73tTxSxcWSyfJ3m4DKIB9HmNFvd9EIiUG0B9CaQBQu7CHyvGr6L45Wmq9UVwoswwb6XwmXgpszKqvsBICtNBNz9LImlKEw18o3fEb/13sfekZccdH2Gvl7LHo0e4g6/YI197fswpF4ztNUqF6ScQk3DF1l70hDrZvM7PqY2uMxDDuaMNw/BgipFrUC0mdsJgMwIawoecByNs5YMU1zN/Kpt2C8RRZvOfIO1kwX7SnILGHp3DGLJlOmi5RIFXgqecyNzR4v/PxowHH9ntV/8Vu64wehbhjObiJJwNqm4r50aJ3a7B8YiSutQqmP1I1EudIR93R3PdYgedZRtGLDi7zstuk2dApLxklWLxb7XVomSxYH2J3nibiGKnBxbPJSdwnAKlOFtCeZE9ns0pW335+KPe/QCZBZSf2UuOFhDBUDdxyDEigNZh9qXb87EratuaZ5u2GpUv9D4iAW+ciuu1oXZamaNT2icVhkX7TH0w41K3AI8OYbpN7mUgCBA45w6L/kb0YbSdQsf2QZlc4dWgo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
