travis:
  secure:
    BINSTAR_TOKEN: bv7OByjGrz9TiwTpLQa5LL0wjqlzEKpS+85Un71cL1fW1zgKzrlwi5ivX0zUv9mFScywpDyYHWNmxYN7CBft/p9zK7HxWimJghqCNAV8yGJnCkvhvgsX0AQE7pJi7vem8w3GhGPgfTr2FpjV2RCLOI+JG7sHdddn8vKQlD2xcQ3z5hWRoMkGHQ4aSS/GoOQ36NoouTjUNkAKg0vgJqU/Nc1UPxhecJJguD9UpXc9LWqCS37ZFNTKSu/H30mPnj1MQlHPodeIaTS74rHoPyI9EP4RO+M2ARrA47hROzhBFrUsD+SAJZynR4iw/RfHIW7zAlp0abTprzf7VIB6yMAkH5GU+JnkICPOkC21ei/DxVQgHDZB/Wqs10Bu0LZdK/cLhdgsamtNVdeiFkX7crJfq8U9X3CrF492zBs4PBYvVhGf2yQNG7Jm1VXuC8tR90of6kDmFC4bO89yJcUxpTHSDG0AS3khRqa6opZOVZBkZIFudrdXK4NWKJUW6/UIre3m2jjGD2EyiGI3ycJmKm5pYVCRz2lIs2Y3JKVktWrCkfkUvDcyNLL0IsOt5qwMS6nL/O9uEu2w6+ho0LjSNp0sShOGz05T5QbUYXxLiwGpm825ft5S0EsF+Hdvx3qfxvN176AqIWT+Hnz/omW+HKVchiFNTBpWl7h4KOJsW3NJaoY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
