travis:
  secure:
    BINSTAR_TOKEN: bcTJ4iIVsQH4PV4asoo3yE5Z+MwIiQXdNg7eOypk5Ah7rSGXt14gf4Hr2iCCMFwHNy0a8SXtfVJAOBKnDiWcB4y0sqTuKPH/cGcPCYnoKawDAhFJExzIcIdpK/q2vLBdayBxAsbnh9Oe3lC7DZzpsG1RBJhsl0xPwzUxkQ8NJt/l8RLl2kzftQU5erUAV7T8MJiTTAaJtqJwMfOXbpuABTbhECeygL+/5gZWJbe919yCtn9BJOibZG8m6dN3Llr9mCcmyFZkRX64OMTVz7Z+tBRawjJaSxUDctgX+er99PsldTZ55q4GHZwF9P4to6GhvDeFIOXLk5JhOj61rCO6muGvm03s/y+W0KiTFsa2SRsvTZrH4eMXK7zo0zw+oIei+BGvlWo1X/FehDFydSp5ujC/hDC6QgVXLKIMZtOg104BhPZz8Y0+OtwFHvEsW0VwZBr/kffSJ1JrQ0WSWxh/1l0OJULXEFA6SWjC1S9jdJBKi2Hp7OX+PTZAmb1t52huYIQivhrv7r6xfycbC4QRWVFzNpJdXA13UvUB/oII03s7riWRPiqy41TV0ywRrkGH3u+9CMiFWc6Lch06kpkH74wBQmsaRA/gPjQS0jCYXdg5f/wLMG6EkodDqy16enyGDGJCV5LKpHw1NIM/GoptDQ5XrEN6GuBt0MqwJnQU63A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
